Repository ThePhD/sol2, pull requests merged in 2022-06, with the labels that each got.

#1352 CMake: Build LuaJIT: use copy_if_different
  cmake/Packages/FindLuaBuild/LuaJIT.cmake
Labels: Thank.You, Bright.Future, Build

#1355 fix #1354
  include/sol/stack_push.hpp
Labels: Thank.You, Bright.Future, Bug.Derp

#1371 @zach2good Add static_cast to unique_index arg to silence MSVC warning
  include/sol/stack.hpp
Labels: Thank.You, Bug.Derp, Build
